wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.19
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1766868296
    t:
      1:
      - 1
      - 30
      - 55
      - 105
      2:
      - 1
      - 30
      - 55
      - 105
      3:
      - 2
      - 13
      - 23
      4: 3.10.19
      5: 0.17.9
      8:
      - 1
      - 5
      13: linux-x86_64
