name: MARL
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.19=py310h8a20257_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h7354ed3_4
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h139afa4_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py310ha78b2d2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - agilerl==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - blake3==1.0.8
      - cachetools==6.2.4
      - cbor2==5.7.1
      - certifi==2025.11.12
      - cffi==2.0.0
      - cfgv==3.5.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - compressed-tensors==0.10.2
      - contourpy==1.3.2
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - datasets==4.4.2
      - deepspeed==0.17.6
      - depyf==0.19.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dm-tree==0.1.9
      - dnspython==2.8.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - email-validator==2.3.0
      - fastapi==0.127.0
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.8.0
      - fastar==0.8.0
      - fastrand==1.8.0
      - fastrlock==0.8.3
      - filelock==3.20.1
      - flatten-dict==0.4.2
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-auth==2.45.0
      - google-cloud-core==2.5.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.8.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - gymnasium==1.2.3
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - identify==2.6.15
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - interegular==0.3.3
      - ipywidgets==8.1.8
      - jax==0.4.38
      - jax-jumpy==1.0.0
      - jaxlib==0.4.38
      - jinja2==3.1.6
      - jiter==0.12.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.2.2
      - lazy-loader==0.4
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - lz4==4.4.5
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - minari==0.5.3
      - mistral-common==1.8.8
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - ninja==1.13.0
      - nodeenv==1.10.0
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - openai==1.90.0
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - orjson==3.11.5
      - ormsgpack==1.7.0
      - outlines-core==0.2.10
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - peft==0.15.2
      - pillow==12.0.0
      - pre-commit==3.8.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pydantic-settings==2.12.0
      - pygame==2.6.1
      - pymunk==6.11.1
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.3
      - ray==2.53.0
      - redis==4.6.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - rpds-py==0.30.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.48.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - skrl==1.4.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - stable-baselines3==2.7.1
      - starlette==0.50.0
      - supersuit==3.10.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensordict==0.8.3
      - termcolor==1.1.0
      - tifffile==2025.5.10
      - tiktoken==0.12.0
      - tinyscaler==1.2.8
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchrl==0.10.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.3.1
      - typer==0.20.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - ucimlrepo==0.0.3
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - virtualenv==20.35.4
      - vllm==0.10.0
      - wandb==0.17.9
      - watchfiles==1.1.1
      - websockets==15.0.1
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - xformers==0.0.31
      - xgrammar==0.1.21
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/terra/anaconda3/envs/MARL
